on: 
  workflow_dispatch:
name: Download OS101 Source
jobs:
  wget:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: List files, see what actually exists
        run: ls
      - name: Download a file
        run: wget https://raw.githubusercontent.com/nasa/Transform-to-Open-Science/open-science-101/README.md -O download/folder/target.md
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}